Update assemble

diff --git a/.s2i/bin/assemble b/.s2i/bin/assemble
--- a/.s2i/bin/assemble
+++ b/.s2i/bin/assemble
@@ -1,8 +1,9 @@
-######## CUSTOMIZATION STARTS HERE ############
-echo "---> Installing application source"
-cp -Rf /tmp/src/* ./
-DATE=`date "+%b %d, %Y @ %H:%M %p"`
-echo "---> Creating info page"
-echo "Page built on $DATE" >> ./info.html
-echo "Proudly served by Apache HTTP Server version $HTTPD_VERSION" >> ./info.html
-######## CUSTOMIZATION ENDS HERE ############
+echo "Making pre-invocation changes..."
+/usr/libexec/s2i/assemble
+rc=$?
+if [ $rc -eq 0 ]; then
+    echo "Making post-invocation changes..."
+else
+    echo "Error: assemble failed!"
+fi
+exit $rc
